import {Platform, StyleSheet} from 'react-native';
import config from '../../config';
import {getStatusBarHeight} from '../../Util/Utilities';

export default styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    paddingTop: getStatusBarHeight(),
    backgroundColor: config.Constant.COLOR_WHITE,
  },
  userName: {
    fontFamily: config.Constant.Font_Bold,
    fontSize: 18,
    color: config.Constant.COLOR_BLACK,
    width: '90%',
    textAlign: 'left',
    letterSpacing: 1.1,
    alignSelf: 'center',
  },
  locationTxt: {
    fontFamily: config.Constant.Font_Regular,
    fontSize: 15,
    color: config.Constant.COLOR_LIGHT_GREY,
    width: '90%',
    textAlign: 'left',
    letterSpacing: 0.84,
    marginTop: 10,
    alignSelf: 'center',
  },
  locationPlaceTxt: {
    fontFamily: config.Constant.Font_Semi_Bold,
    fontSize: 15,
    color: config.Constant.COLOR_BLACK,
    flex: 1,
    textAlign: 'left',
    letterSpacing: 0.98,
    paddingHorizontal: 5,
  },
  changeTxt: {
    fontFamily: config.Constant.Font_Regular,
    fontSize: 13,
    color: config.Constant.COLOR_TAB,
    textAlign: 'left',
    letterSpacing: 0.84,
    paddingHorizontal: 5,
  },
  rowContainer: {
    flexDirection: 'row',
    width: '90%',
    alignSelf: 'center',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  smallIcon: {
    width: 15,
    height: 15,
    tintColor: config.Constant.COLOR_TAB,
  },
  rowViewStyle: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    width: '90%',
    paddingTop: 25,
    paddingBottom: 15,
    alignSelf: 'center',
    alignItems: 'center',
  },
  rowTitle: {
    fontFamily: config.Constant.Font_Semi_Bold,
    fontSize: 20,
    color: config.Constant.COLOR_BLACK,
    fontWeight: '600',
    flex: 1,
    letterSpacing: 1.4,
    textAlign: 'left',
  },
  rowBtnTitle: {
    fontFamily: config.Constant.Font_Regular,
    fontSize: 14,
    color: config.Constant.COLOR_LIGHT_GREY,
    fontWeight: '600',
    letterSpacing: 1,
  },
  serviceView: {
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
    height: 95,
  },
  serviceImgView: {
    backgroundColor: '#711CD3',
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 5,
  },
  serviceName: {
    fontFamily: config.Constant.Font_LIGHT,
    fontSize: 15,
    color: config.Constant.COLOR_BLACK,
  },
  btnStyle: {
    width: '90%',
    marginTop: 20,
    marginBottom: 15,
    alignSelf: 'center',
  },
  searchBar: {
    width: '90%',
    padding: 10,
    backgroundColor: config.Constant.COLOR_INPUT,
    marginTop: 10,
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchIcon: {
    width: 20,
    height: 20,
    tintColor: config.Constant.COLOR_GREY,
    marginHorizontal: 10,
  },
  inputStyle: {
    padding: 0,
    flex: 1,
    color: config.Constant.COLOR_BLACK,
    textAlign: config.Constant.isRTL ? 'right' : 'left',
  },
  catView: {
    flexDirection: 'row',
    alignSelf: 'center',
    width: '90%',
    flexWrap: 'wrap',
    marginTop: 10,
  },
  wrapTxtRow: {
    fontFamily: config.Constant.Font_Regular,
    fontSize: 15,
    letterSpacing: 0.84,
    color: config.Constant.COLOR_WHITE,
    marginRight: 10,
    paddingTop: Platform.OS == 'ios' ? 3 : 2,
    paddingBottom: Platform.OS == 'ios' ? 4.5 : 1.5,
    maxWidth: config.Constant.SCREEN_WIDTH * 0.67,
  },
  wrapTxtRemove: {
    fontFamily: config.Constant.Font_Bold,
    fontSize: 15,
    color: config.Constant.COLOR_WHITE,
    marginHorizontal: 5,
  },
  wrapRow: {
    flexDirection: 'row',
    backgroundColor: config.Constant.COLOR_TAB,
    marginRight: 15,
    marginVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 50,
    alignItems: 'center',
  },
  deviderLine: {
    height: '100%',
    width: 2,
    marginHorizontal: 5,
    backgroundColor: config.Constant.COLOR_WHITE,
  },
  selectedItemsView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    alignSelf: 'center',
    marginVertical: 10,
    alignItems:'center'
  },
  searchName: {
    fontFamily: config.Constant.Font_Regular,
    fontSize: 16,
    color: config.Constant.COLOR_BLACK,
    flex: 1,
    textAlign: 'left',
    letterSpacing: 0.98,
    paddingHorizontal: 5,
  },
  searchType: {
    fontFamily: config.Constant.Font_Italic_LIGHT,
    fontSize: 16,
    color: config.Constant.COLOR_BLACK,
    letterSpacing: 0.98,
  },
  dialogStyle: {
    backgroundColor: config.Constant.COLOR_TRANSPARENT,
    borderRadius: 0,
    maxHeight: config.Constant.SCREEN_HEIGHT * 0.8,
    paddingTop: 10,
  },
  dialogContent: {
    backgroundColor: config.Constant.COLOR_WHITE,
    width: '100%',
    alignSelf: 'center',
    borderTopRightRadius: 35,
    borderTopLeftRadius: 35,
    paddingBottom: 10,
    shadowColor: config.Constant.COLOR_GREY,
    shadowOffset: {
      width: 1,
      height: 1,
    },
    height: config.Constant.SCREEN_HEIGHT * 0.6,
    shadowRadius: 10,
    shadowOpacity: 1,
    elevation: 12,
  },
  emptyIcon:{
    borderRadius:30,
    borderWidth:3,
    height:20,
    width:20,
    borderColor:'#0000000F',
    justifyContent:'center',
    alignItems:'center'
  },
  filledIcon:{
    borderRadius:30,
    borderWidth:0,
    height:14,
    width:14,
    backgroundColor: config.Constant.COLOR_TAB,

  },
});
