import {StyleSheet} from 'react-native';
import config from '../../config';
import {getStatusBarHeight} from '../../Util/Utilities';

export default styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  bannerImg: {
    width: config.Constant.SCREEN_WIDTH,
    height: config.Constant.SCREEN_HEIGHT / 2,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: -1,
  },
  bottomView: {
    width: config.Constant.SCREEN_WIDTH,
    backgroundColor: 'white',
    borderTopRightRadius: 35,
    borderTopLeftRadius: 35,
    marginTop: 10,
    alignItems: 'center',
  },
  bottomScrollView: {
    width: config.Constant.SCREEN_WIDTH,
    backgroundColor: config.Constant.COLOR_TRANSPARENT,
    //paddingTop:config.Constant.SCREEN_HEIGHT / 1.8
  },
  titleTxt: {
    textAlign: 'center',
    fontSize: 24,
    fontFamily: config.Constant.Font_Bold,
    marginTop: 20,
    marginBottom: 5,
    color: config.Constant.COLOR_BLACK,
  },
  titleDesTxt: {
    textAlign: 'center',
    fontSize: 14,
    fontFamily: config.Constant.Font_Regular,
    marginBottom: 20,
    color: config.Constant.COLOR_LIGHT_GREY,
  },
  forgotTxt: {
    textAlign: 'center',
    fontSize: 15,
    fontFamily: config.Constant.Font_Regular,
    marginBottom: 20,
    color: config.Constant.COLOR_BLACK,
  },
  dontTxt: {
    textAlign: 'center',
    fontSize: 15,
    marginBottom: 20,
    fontFamily: config.Constant.Font_Regular,
    color: config.Constant.COLOR_LIGHT_GREY,
  },
  signUpTxt: {
    textAlign: 'center',
    fontSize: 15,
    fontFamily: config.Constant.Font_Regular,
    color: config.Constant.COLOR_BTN,
  },
  inputStyle: {width: '85%', marginVertical: 5},
  btnStyle: {width: '85%', marginTop: 20, marginBottom: 15},

  headerStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    alignItems: 'center',
    alignSelf: 'center',
  },
  uploadStyle: {
    // flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    // alignItems: 'center',
    // alignSelf: 'center',
  },
  headerBorderStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 60,
    alignSelf: 'flex-start',
    marginBottom: 20,
    marginTop: 5,
    marginLeft: config.Constant.SCREEN_WIDTH * 0.05,
    borderBottomWidth: 1.5,
    borderBottomColor: config.Constant.COLOR_TAB,
  },
  descStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 15,
    backgroundColor: config.Constant.COLOR_LIGHT_BG,
    borderRadius: 100,
  },
  uploadTitle: {
    fontSize: 19,
    fontFamily: config.Constant.Font_Medium,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'left',
    flex: 1,
    marginTop: 8,
  },
  descTitle: {
    fontSize: 19,
    fontFamily: config.Constant.Font_Medium,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'left',
    flex: 1,
    marginTop: 10,
  },
  qtyTitle: {
    fontSize: 19,
    fontFamily: config.Constant.Font_Semi_Bold,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'center',
    width: 80,
  },
  priceTitle: {
    fontSize: 19,
    fontFamily: config.Constant.Font_Semi_Bold,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'right',
    width: 70,
  },
  mapBox: {
    borderRadius: 20,
    width: '90%',
    alignSelf: 'center',
  },
  selectFile: {
    fontFamily: config.Constant.Font_Regular,
    fontSize: 16,
    color: config.Constant.COLOR_BLACK,
    // flex: 1,
    // borderWidth:1,
    marginTop:8,
    textAlign: 'left',
    letterSpacing: 0.98,
  },
  methodName: {
    fontFamily: config.Constant.Font_Regular,
    fontSize: 16,
    color: config.Constant.COLOR_BLACK,
    flex: 1,
    textAlign: 'left',
    letterSpacing: 0.98,
  },
  selectedItemsViewMethod: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    alignSelf: 'center',
    marginTop: 10,
    alignItems: 'center',
  },
  emptyIconMethod: {
    borderRadius: 30,
    borderWidth: 3,
    height: 20,
    width: 20,
    borderColor: '#0000000F',
    justifyContent: 'center',
    alignItems: 'center',
  },
  filledIconMethod: {
    borderRadius: 30,
    borderWidth: 0,
    height: 14,
    width: 14,
    backgroundColor: config.Constant.COLOR_TAB,
  },
});
