import {Platform, StyleSheet} from 'react-native';
import config from '../../config';
import {getStatusBarHeight} from '../../Util/Utilities';

export default styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',

    backgroundColor: config.Constant.COLOR_WHITE,
  },
  rowContainer: {
    flexDirection: 'row',
    width: '100%',
    alignSelf: 'center',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: getStatusBarHeight(),
    paddingBottom: 15,
    paddingHorizontal: config.Constant.SCREEN_WIDTH * 0.05,
    backgroundColor: 'white',
    shadowColor: config.Constant.COLOR_GREY,
    shadowOffset: {
      width: 0.5,
      height: 0.5,
    },
    shadowRadius: 0.5,
    shadowOpacity: 0.4,
    elevation: 2,
  },
  smallIcon: {
    width: 20,
    height: 20,
  },
  headerTitle: {
    fontFamily: config.Constant.Font_Bold,
    fontSize: 18,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'center',
    letterSpacing: 1.26,
    alignSelf: 'center',
  },

  reviewTxt: {
    fontSize: 13,
    fontFamily: config.Constant.Font_Roboto_Light_Italic,
    color: config.Constant.COLOR_BLACK,
    letterSpacing: 0.9,
    textAlign: 'left',
    flex: 1,
    marginTop: -10,
    marginLeft: 40,
  },
  timeTxt: {
    fontSize: 12,
    fontFamily: config.Constant.Font_LIGHT,
    color: config.Constant.COLOR_GREY,
    letterSpacing: 0.98,
  },
  reviewName: {
    fontSize: 15,
    flex: 1,
    fontFamily: config.Constant.Font_Semi_Bold,
    color: config.Constant.COLOR_BLACK,
    letterSpacing: 0.98,
    textAlign: 'left',
    marginBottom: 5,
  },
  reviewBox: {
    backgroundColor: config.Constant.COLOR_WHITE,
    borderRadius: 10,
    paddingVertical: 10,
    marginBottom: 10,
    width: '90%',
    alignSelf: 'center',
  },
  serviceRowView: {
    flexDirection: 'row',
    alignSelf: 'center',
    marginVertical: 10,
    alignItems: 'center',
  },
  headerStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    alignItems: 'center',
    alignSelf: 'center',
  },
  headerBorderStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 60,
    alignSelf: 'flex-start',
    marginBottom: 20,
    marginTop: 5,
    marginLeft: config.Constant.SCREEN_WIDTH * 0.05,
    borderBottomWidth: 1.5,
    borderBottomColor: config.Constant.COLOR_TAB,
  },
  descStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '95%',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 15,
    padding: config.Constant.SCREEN_WIDTH * 0.025,
    backgroundColor: config.Constant.COLOR_LIGHT_BG,
    borderRadius: 100,
  },
  descTitle: {
    fontSize: 19,
    fontFamily: config.Constant.Font_Semi_Bold,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'left',
    flex: 1,
    letterSpacing: 1.4,
  },
  qtyTitle: {
    fontSize: 19,
    fontFamily: config.Constant.Font_Semi_Bold,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'center',
    width: 80,
  },
  priceTitle: {
    fontSize: 19,
    fontFamily: config.Constant.Font_Semi_Bold,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'right',
    width: 70,
  },
  descData: {
    fontSize: 15,
    fontFamily: config.Constant.Font_Regular,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'left',
    flex: 1,
  },
  qtyData: {
    fontSize: 15,
    fontFamily: config.Constant.Font_Regular,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'center',
    width: 80,
  },
  priceData: {
    fontSize: 15,
    fontFamily: config.Constant.Font_Regular,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'right',
    width: 70,
  },
  descSubTotal: {
    fontSize: 15,
    fontFamily: config.Constant.Font_Semi_Bold,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'left',
    flex: 1,
  },
  qtySubTotal: {
    fontSize: 15,
    fontFamily: config.Constant.Font_Semi_Bold,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'center',
    width: 80,
  },
  priceSubTotal: {
    fontSize: 15,
    fontFamily: config.Constant.Font_Semi_Bold,
    color: config.Constant.COLOR_BLACK,
    textAlign: 'right',
    width: 70,
  },
  borderView: {
    width: '45%',
    alignSelf: 'center',
    borderBottomWidth: 1,
    marginTop: 10,
    borderColor: config.Constant.COLOR_BORDER_COLOR,
  },
  btnStyle: {
    width: '85%',
    marginTop: 30,
    marginBottom: 20,
    alignSelf: 'center',
  },
  btnEmptyStyle: {
    backgroundColor: config.Constant.COLOR_WHITE,
    borderRadius: 20,
    borderColor: config.Constant.COLOR_BTN,
    borderWidth: 1,
    height:45,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    width: '85%',
    flexDirection: 'row',
    paddingVertical: 8,
    marginVertical: 30,
  },
  moneyTxt: {
    fontFamily: config.Constant.Font_Roboto_Bold,
    fontSize: 33,
    color: config.Constant.COLOR_TAB,
    alignSelf: 'center',
    marginTop: 30,
    marginBottom: 15,
  },
  balanceTxt: {
    fontFamily: config.Constant.Font_Semi_Bold,
    fontSize: 21,
    color: config.Constant.COLOR_BLACK,
    alignSelf: 'center',
    letterSpacing: 1.4,
  },
  notificationView: {
    width: config.Constant.SCREEN_WIDTH * 0.95,
    alignSelf: 'center',
    paddingHorizontal: config.Constant.SCREEN_WIDTH * 0.05,
    marginVertical: 5,
    paddingVertical: 10,
    backgroundColor: config.Constant.COLOR_LIGHT_BACKGROUND,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rowView: {
    flex: 1,
  },
  rowViewBottom: {},
  rowTitle: {
    fontFamily: config.Constant.Font_Bold,
    fontSize: 16,
    color: config.Constant.COLOR_BLACK,
    letterSpacing: 0.98,
    marginBottom: 5,
    textAlign: 'left',
  },
  rowDesc: {
    fontFamily: config.Constant.Font_Roboto_Italic,
    fontSize: 14,
    color: config.Constant.COLOR_EXTRA_LIGHT,
    letterSpacing: 0,
  },
  amoutStaus: {
    fontFamily: config.Constant.Font_Roboto_Bold,
    fontSize: 16,
    color: config.Constant.COLOR_LIGHT_GREEN,
    letterSpacing: 0,
    textAlign: 'right',
  },
  txtStyle: {
    fontFamily: config.Constant.Font_Regular,
    color: config.Constant.COLOR_TAB,
    fontSize: 18,
    letterSpacing: 1.26,
  },
  emptyString: {
    fontFamily: config.Constant.Font_Roboto_Italic,
    fontSize: 18,
    width: config.Constant.SCREEN_WIDTH * 0.8,
    textAlign:'center',
    alignSelf:'center',
    color: config.Constant.COLOR_DARK_GREY,
  },
});
