export default {
  app:'dresser',
  welcomeBack: `Welcome Back`,
  loginToAcc: `Login to your account`,
  email: `Email`,
  password: `Password`,
  login: `Login`,
  forgotYourPass: `Forgot your password?`,
  dontHavAcc: `Don't have an account?`,
  signUp: `Sign Up`,
  signIn: `Sign In`,
  createAccount: `Create Account`,
  registerNewAccount: `Register new account`,
  alreadyHaveAc: `Already have an account?`,
  name: `Name`,
  emailAddress: `Email address`,
  phoneNumber: `Phone number`,
  confirmPassword: `Confirm password`,
  referrerNumber: `Referrer phone number`,
  otpHasSendToemail: `OTP has been sent to your email id and phone number.`,
  otpIsSendToemail: `OTP is sent to your email id and phone number.`,
  otpSendTitle: `OTP has been sent.`,
  enterOtp: `Enter OTP`,
  resend: `Resend`,
  submit: `Submit`,
  forgotPass: `Forgot Password`,
  enterYourEmail: `Please enter your registered email address.`,
  resetPass: `Reset Password`,
  back: `Back`,
  createNewPass: `Create New Password`,
  enterNewPass: `Enter new password`,
  newPass: `New Password`,
  confirmPass: `Confirm Password`,
  create: `Create`,
  myorders: `My Orders`,
  wallet: 'Wallet',
  support: `Support`,
  SwitchToArabic: `Switch to Arabic`,
  SwitchToEnglish: `Switch to English`,
  logout: 'Logout',
  seachService: `Search services`,
  topService: `Top Services`,
  viewAll: `View all`,
  nearByHairDresser: `Near by Hair Dressers`,
  specialPackage: `Special Package & Offers`,
  previouslyHired: `Previously Hired`,
  hello: 'Hello',
  yourLocation: `Your location`,
  CHANGE: `CHANGE`,
  change: `Change`,
  services: `Services`,
  searchHairDresser: `Search Hair dresser`,
  notification: `Notifications`,
  wishlist: `Wishlist`,
  profile: `Profile`,
  phone: `Phone`,
  email: `Email`,
  location: `Location`,
  editProfile: `Edit Profile`,
  changePassword: `Change Password`,
  bookNow: `Book Now`,
  about: `About`,
  services: `Services`,
  reviews: `Reviews`,
  yourOrders: `Your Orders`,
  reviewOrders: `Review Order`,
  service: `Service`,
  qty: `Qty`,
  price: `Price`,
  SubTotal: `Sub-total`,
  fees: `Fees`,
  confirm: `Confirm`,
  call: `Call`,
  checkout: `Checkout`,
  address: `Address`,
  applyCoupon: `Apply Coupon`,
  apply: 'Apply',
  paymentMethod: `Payment Method`,
  enterCouponCode: `Enter Coupon code`,
  creditDebitCard: `Credit / Debit Card`,
  cashOnDelivery: `Cash on delivery`,
  orderProcessing: `Order Processing`,
  wallet: `Wallet`,
  addAmount: `Add Amount`,
  add: `Add`,
  recentTransactions: `Recent Transactions`,
  BALANCE: `BALANCE`,
  loadMore: `Load more`,
  amountCredited: `Amount credited`,
  amountDebited: `Amount debited`,
  generalProfile: `General Profile`,
  requestSend: `Request sent`,
  waitFor: `Wait for`,
  noResponce: `No Response`,
  tryAnotherDresser: `Please try another hairdresser.`,
  selectAnotherDressser: `Select Another Hairdresser`,
  tryAgain: `Try again`,
  requestRejected: `Request Rejected`,
  oldPass: `Old Password`,
  weAreProcessing: `We are processing your order`,
  dresserOnWay: `Hairdresser on the way`,
  workInProgress: `Work in progress.`,
  orderCompleted: `Order Completed`,
  amountPaidInCash: `Amount to be paid in cash.`,
  track: `Track`,
  save: `Save`,
  enterValidEmail: `Enter valid email address`,
  enterValidPass: `Password field is required`,
  cancel: `Cancel`,
  inProgress: 'In progress',
  away: 'away',
  Total: `Total`,
  enterValidName: `Enter valid name`,
  enterValidPhone: `Enter valid phone number`,
  enterValidRePass: `Confirm password is not matched with password`,
  enterValidRefNum: `Enter valid referrer phone number`,
  recentReview: `Recent Reviews`,
  totalIncome: `Total\nIncome`,
  completedOrders: `Completed\nOrders`,
  onlineStatus: `Online Status`,
  online: 'Online',
  orderIncoming: `Order Incomming`,
  orderWillCacnel: `Order will automatically cancel in`,
  accept: `Accept`,
  reject: `Reject`,
  addService: 'Add Service',
  viewProfile: "View Profile",
  completed: `Completed`,
  goingToLocation: `Going to location`,
  complete: `Complete`,
  dispute: `Dispute`,
  enterAmount: `Enter amount\n received.`,
  sar: `SAR`,
  fillTheAmount: `Fill the amount first`,
  explainIssue: `Kindly explain your issue.`,
  loading: 'Loading...',
  error: 'Error',
  no_internet_title: 'Internet Error',
  no_internet_msg: 'Please check your internet connection',
  success: 'Success',
  somethingWentWrong: `Something went wrong try again after sometime`,
  enterValidPassLong: `Please fill password at least 8 character long`,
  wrongOtp: `Otp is incorrect`,
  enterValidNewRePass: `Confirm password is not matched with new password`,
  enterValidOldPass: `Old Password field is required`,
  enterValidNewPass: `New Password field is required`,
  selectOption: 'Select option for image selection',
  fromGallery: 'From Gallery',
  fromCamera: 'From Camera',
  selectCategory: 'Select Category',
  subCategory: 'Sub-category',
  selectCat: 'Please select Category.',
  selectSubCat: 'Please select Sub-category.',
  fillSar: 'Fill the amount.',
  noNotification: 'There are no notifications.',
  noFavorites: 'You are not added any favorite haidresser yet.',
  noOrder: 'There are no orders.',
  noReviews: 'There are no reviews.',
  tax: 'Tax',
  promoCode: 'Coupon Code',
  startProcess: 'Start Process',
  giveFeedback: 'Give Feedback',
  postExperience: 'Post your experience',
  reqestTimeot: 'Request Timeout',
  reqestCancel: 'Request Canceled',
  withdrawAmount: `Withdraw Amount`,
  noWalletHistory: 'There are no transactions.',
  offline: 'offline',
  add_someting_about_you: 'Add someting about you',
  add_Services: 'Add some services',
  fillTheRightAmount:
    'Please add the total amount of order or add 0 if customer not pay',
  pleaseAddYouReview: 'Please add review',
  locationError:
    'Please allow location permission from setting to use this application.',
  otpHasSendToCustomerEmail: `OTP has been sent to customer's email id and phone number.`,
  otpIsSendToCustomerEmail: `OTP is sent to customer's email id and phone number.`,
  updateService: 'Update Service',
  rejectionReason: 'Rejection Reason',
  requestCancelOrder: 'Request canceled by user',
  hideMap: 'Hide Map',
  showMap: 'Show Map',

  totalTax: `Total Tax Paid`,
  allTypeMethod: 'All Methods',
  waitingToPayment: 'Waiting for client to pay',
  deleteAccount: "Delete Account",
  deleteAccountMsg: "Are you sure you want to delete your account?",
  No: "No",
  Yes: "Yes",
  Done: 'Done',
  Ok: 'Ok',
  CancelOrder: "Cancel Order",
  paymentReqestTimeot: 'Payment Request Timeout',
  PaymentAlertHeader: "Payment",
  WaitForClientPay:"Wait for client pay",
  serviceChargeSAR:`Service Charge(SAR)`,
  appFeesSAR:`App Fees(SAR)`,
  youWillReceiveSAR: `You'll Receive(SAR)`,
  bankAccNum: 'Bank Account Number',
  enterValid24DigitBankAccountNumber: `Enter valid 24 digit bank account number`,
  nameInBankAcc: `Name in Bank`,
  agree:`Agree `,
  termsAndCondition: `Terms And Condition`,
  pleaseAgreeTermsAndConditions:`please agree terms and conditions`,
  clear_all:"Clear all",
  Upload_iban:"Upload iban",
  select_file:"Select File",
  upload_id:"Upload id",
  upload_your_id:"Please upload your id",
  upload_your_iban:"Please upload your iban",
  PaymentMethods: 'Payment Methods',
  ClickMethod: 'Click one of the methods',
  MAKEPAYMENT:"Make Payment",
  selectPaymentMethod:"Please select payment method",
  paymentSuccess: 'Payment successfully!',
};
