export default {
  app:'dresser',
  welcomeBack: `مرحبا بعودتك`,
  loginToAcc: `تسجيل الدخول إلى حسابك`,
  email: `البريد الالكتروني`,
  password: `كلمة المرور`,
  login: `تسجيل الدخول`,
  forgotYourPass: `نسيت كلمة المرور؟`,
  dontHavAcc: `ليس لديك حساب؟`,
  signUp: `تسجيل`,
  signIn: `تسجيل الدخول`,
  createAccount: `انشئ حساب جديد`,
  registerNewAccount: `تسجيل حساب جديد`,
  alreadyHaveAc: `هل لديك حساب؟`,
  name: `الاسم`,
  emailAddress: `البريد الالكتروني`,
  phoneNumber: `رقم الهاتف`,
  confirmPassword: `تأكيد كلمة المرور`,
  referrerNumber: `رقم هاتف من قام بدعوتك`,
  otpHasSendToemail: `تم إرسال رمز التفعيل الى بريدك الالكتروني ورقم الهاتف الخاص بك`,
  otpIsSendToemail: `تم إرسال رمز التفعيل الى بريدك الالكتروني ورقم الهاتف الخاص بك`,
  otpSendTitle: `تم إرسال رمز التفعيل`,
  enterOtp: `إدخال رمز التفعيل`,
  resend: `إعادة الارسال`,
  submit: `تأكيد`,
  forgotPass: `نسيت كلمة المرور`,
  enterYourEmail: `الرجاء إدخال عنوان بريدك الإلكتروني المسجل`,
  resetPass: `إعادة تعيين كلمة المرور`,
  back: `العودة الى الخلف`,
  createNewPass: `إنشاء كلمة مرور جديدة`,
  enterNewPass: `ادخل كلمة مرور جديدة`,
  newPass: `كلمة مرور جديدة`,
  confirmPass: `تأكيد كلمة المرور`,
  create: `إنشاء`,
  myorders: `طلباتي`,
  wallet: 'المحفظة',
  support: `الدعم الفني`,
  SwitchToArabic: `التغيير الى اللغة العربية`,
  SwitchToEnglish: `Switch To English`,
  logout: 'تسجيل الخروج',
  seachService: `البحث عن خدمة`,
  topService: `افضل الخدمات`,
  viewAll: `عرض الكل`,
  nearByHairDresser: `الاخصائيات القريبه منك`,
  specialPackage: `الباقات والعروض الخاصة`,
  previouslyHired: `تم تعيينه مسبقًا`,
  hello: 'مرحبًا',
  yourLocation: `موقعك الحالي`,
  CHANGE: `تغيير`,
  change: `تغيير`,
  services: `الخدمات`,
  searchHairDresser: `البحث عن اخصائية`,
  notification: `الإشعارات`,
  wishlist: `المفضلة`,
  profile: `حسابي`,
  phone: `رقم الهاتف`,
  email: `البريد الالكتروني`,
  location: `الموقع`,
  editProfile: `تحديث حسابي`,
  changePassword: `تغيير كلمة المرور`,
  bookNow: `الحجز الان`,
  about: `من نحن`,
  services: `الخدمات`,
  reviews: `التقييمات`,
  yourOrders: `الطلبات الخاصة بك`,
  reviewOrders: `مراجعة الطلب`,
  service: `الخدمات`,
  qty: `الكمية`,
  price: `السعر`,
  SubTotal: `المجموع`,
  fees: `الرسوم`,
  confirm: `تأكيد`,
  call: `اتصال`,
  checkout: `الدفع`,
  address: `العنوان`,
  applyCoupon: `إضافة كود خصم`,
  apply: 'تفعيل',
  paymentMethod: `وسيلة الدفع`,
  enterCouponCode: `أدخل رمز كود الخصم`,
  creditDebitCard:`الدفع الالكتروني`,// creditDebitCard: `بطاقة الائتمان`,
  cashOnDelivery: `الدفع نقدا`,
  orderProcessing: `معالجة الطلب`,
  wallet: `المحفظة`,
  addAmount: `أضف المبلغ`,
  recentTransactions: `العمليات السابقة`,
  BALANCE: `رصيد حسابك`,
  loadMore: `تحميل المزيد`,
  amountCredited: `المبلغ المضاف`,
  amountDebited: `المبلغ المخصوم`,
  generalProfile: `الحساب العام`,
  requestSend: `تم ارسال الطلب`,
  waitFor: `أنتظر لأجل`,
  noResponce: `لا يوجد رد`,
  tryAnotherDresser: `يمكنك اختيار اخصائية اخرى.`,
  selectAnotherDressser: `اختر اخصائية اخرى`,
  tryAgain: `حاول مرة اخرى`,
  requestRejected: `تم رفض الطلب`,
  oldPass: `كلمة المرور القديمة`,
  weAreProcessing: `جاري معالجة الطلب `,
  dresserOnWay: `الاخصائية في الطريق`,
  workInProgress: `العمل قيد التنفيذ`,
  orderCompleted: `تم تنفيذ الطلب`,
  amountPaidInCash: `المبلغ الواجب دفعه نقدا`,
  track: `تتبع`,
  save: `حفظ`,
  cancel: `إلغاء`,
  inProgress: 'جاري العمل',
  away: 'بعيدا',
  Total: `الاجمالي`,
  enterValidName: `ادخل اسم صالح`,
  enterValidPhone: `ادخل رقم هاتف صالح`,
  enterValidRePass: `تأكيد كلمة المرور لا يتطابق مع كلمة المرور`,
  enterValidRefNum: `ادخل رقم هاتف صالح`,
  recentReview: `المراجعات الأخيرة`,
  totalIncome: `اجمالي\nالدخل`,
  completedOrders: `محتملة\nطلبات`,
  onlineStatus: `حالة التواجد`,
  online: 'متصل',
  orderIncoming: `طلب وارد`,
  orderWillCacnel: `سيتم إلغاء الطلب تلقائيًا في غضون`,
  accept: `قبول`,
  reject: `رفض`,
  addService: 'اضافة خدمة',
  viewProfile: "خدماتي",
  add: `أضف`,
  completed: `مكتمل`,
  goingToLocation: `الانتقال الى الموقع.`,
  complete: `مكتمل`,
  dispute: `اعتراض`,
  enterAmount: `ادخل المبلغ\n المستلم.`,
  sar: `ريال`,
  fillTheAmount: `ادخل المبلغ المستلم اولا`,
  explainIssue: `يرجى شرح مشكلتك.`,
  loading: 'يرجى الانتظار...',
  error: 'حدث خطا ما',
  no_internet_title: 'خطا في الاتصال بالشبكة',
  no_internet_msg: 'يرجى التحقق من اتصالك بالشبكة',
  success: 'نجحت العملية',
  somethingWentWrong: `حدث خطا ما يرجى معاودة المحاولة لاحقا`,
  enterValidPassLong: `يجب ان تحتوي كلمة المرور على الاقل 8 حروف `,
  wrongOtp: `رمز التفعيل خاطئ`,
  enterValidNewRePass: `تأكيد كلمة المرور لايطابق كلمة المرور الفعلية`,
  enterValidOldPass: `كلمة المرور السابقة مطلوبة`,
  enterValidNewPass: `كلمة المرور الجديدة مطلوب`,
  selectOption: 'حدد الخيار لاختيار الصورة',
  fromGallery: 'من معرض الصور',
  fromCamera: 'التقاط صورة ',
  selectCategory: 'يرجى اختيار صنف',
  subCategory: 'تصنيف فرعي',
  selectCat: 'يرجى اختيار صنف',
  selectSubCat: 'الرجاء تحديد فئة فرعية',
  fillSar: 'يرجى ادخال الكمية',
  noNotification: 'لاتوجد اشعارات',
  noFavorites: 'انت لم تقم بإضافة اي اخصائية بعد',
  noOrder: 'لاتوجد طلبات',
  noReviews: 'لاتوجد مراجعات',
  tax: 'شامل الضريبه وقيمتها',
  promoCode: 'رمز الكوبون',
  startProcess: 'بدء العمل',
  giveFeedback: 'التقييم',
  postExperience: 'اضف تجربتك',
  reqestTimeot: 'طلب مهلة',
  reqestCancel: 'تم إلغاء الطلب',
  withdrawAmount: `سحب المبلغ`,
  noWalletHistory: 'لا يوجد تقييمات.',
  offline: 'غير متصل',
  add_someting_about_you: 'اضف شي عنك',
  add_Services: 'اضف بعض الخدمات',
  fillTheRightAmount:
    'يرجى إضافة المبلغ الإجمالي للطلب أو إضافة 0 إذا لم يدفع العميل',
  pleaseAddYouReview: 'يرجى إضافة تقييم',
  locationError:
    'يرجى السماح باستخدام الموقع من الإعدادات لاستخدام هذا التطبيق.',
  otpHasSendToCustomerEmail: `تم ارسال رمز التحقق الى هاتفك وبريدك الالكتروني يرجى التحقق.`,
  otpIsSendToCustomerEmail: `تم ارسال رمز التحقق الى هاتفك وبريدك الالكتروني يرجى التحقق.`,
  updateService: 'تحديث الخدمة',
  updateService: 'تحديث الخدمة',
  rejectionReason: 'سبب الرفض',
  requestCancelOrder: 'تم طلب الالغاء من العميل',
  hideMap: 'إخفاء الخريطة',
  showMap: 'عرض الخريطة',
  totalTax: `مجموع الضرائب المدفوعة`,
  allTypeMethod: 'جميع الوسائل',
  waitingToPayment: 'بإنتظار العميل للدفع ',
  deleteAccount: "حذف الحساب",
  deleteAccountMsg: "هل انت متأكد انك تريد حذف حسابك؟",
  No: "لا",
  Yes: "نعم",
  Done: 'تم',
  Ok: `نعم`,
  CancelOrder: "الغاء الطلب",
  paymentReqestTimeot: 'انتهت مهلة الدفع',
  PaymentAlertHeader: "اشعار دفع",
  WaitForClientPay:"انتظار الدفع من العميل",
  serviceChargeSAR:`سعر الخدمه (ريال)`,
  appFeesSAR:`العموله (ريال)`,
  youWillReceiveSAR: `سوف تستلم (ريال)`,
  bankAccNum: 'رقم الحساب / ايبان',
  enterValid24DigitBankAccountNumber: `أدخل رقم حساب مصرفي صالحًا مكونًا من 24 رقمًا`,
  nameInBankAcc: `اسم صاحب الحساب`,
  agree:`الموافقة `,
  termsAndCondition: `على شروط الاستخدام`,
  pleaseAgreeTermsAndConditions:`الرجاء الموافقة على شروط الاستخدام`,
  clear_all:"امسح الكل",
  Upload_iban:"تحميل ايبان",
  select_file:"حدد ملف",
  upload_id:"تحميل معرف",
  upload_your_id:"يرجى تحميل معرفك",
  upload_your_iban:"يرجى تحميل رقم الآيبان الخاص بك",
  PaymentMethods: 'طرق الدفع',
  ClickMethod: 'انقر فوق إحدى الطرق',
  MAKEPAYMENT:"قم بالدفع",
  selectPaymentMethod:"الرجاء تحديد طريقة الدفع",
  paymentSuccess: 'تم الدفع بنجاح!',
};
